plugins {
    id 'java'
    id "de.undercouch.download" version "5.6.0"
    id 'antlr'
}

group = 'at.jku.isse.ecco'
version = '0.1.9'

repositories {
    mavenCentral()
}
dependencies {
    antlr "org.antlr:antlr4:4.13.1"
    implementation "org.antlr:antlr4-runtime:4.13.1"
    implementation 'org.logicng:logicng:2.6.0'


    implementation project(':ecco-base')
    implementation project(':ecco-logic')
    implementation project(':ecco-service')
    testImplementation platform('org.junit:junit-bom:5.9.1')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'org.mockito:mockito-core:4.6.1'
}

def generatedSourceDir = file("${project.projectDir}/src/main/java/at/jku/isse/ecco/adapter/rust/antlr")

tasks.register('addPackageDeclaration') {
    def packageLine = 'package at.jku.isse.ecco.adapter.rust.antlr;\n'
    def targetFiles = [
            file("${generatedSourceDir}/RustLexerBase.java"),
            file("${generatedSourceDir}/RustParserBase.java")
    ]
    onlyIf {
        targetFiles.any { it.exists()}
    }
    doLast {
        targetFiles.each { file ->
            if (file.exists()) {
                def content = file.text
                if (!content.startsWith(packageLine)) {
                    file.text = packageLine + content
                }
            }
        }
    }
}


tasks.register('downloadBaseParserBaselexer', Download) {
    // Downloaded fro antlr/grammars-v4 repository
    // Commit: 998300645c2b8c1e537d308cbe7d2c331ebe7d08
    // Date : 2025-24-11
    def commitHash = '998300645c2b8c1e537d308cbe7d2c331ebe7d08'
    src([
            "https://raw.githubusercontent.com/antlr/grammars-v4/${commitHash}/rust/Java/RustLexerBase.java",
            "https://raw.githubusercontent.com/antlr/grammars-v4/${commitHash}/rust/Java/RustParserBase.java",
    ])
    dest generatedSourceDir
    overwrite true
    quiet true
}

downloadBaseParserBaselexer.finalizedBy addPackageDeclaration

generateGrammarSource {
    dependsOn downloadBaseParserBaselexer
    outputDirectory = generatedSourceDir
    arguments += ['-visitor']
    arguments += ['-package', 'at.jku.isse.ecco.adapter.rust.antlr']
}

generateTestGrammarSource {
    dependsOn downloadBaseParserBaselexer
    outputDirectory = generatedSourceDir
    arguments += ['-package', 'at.jku.isse.ecco.adapter.rust.antlr']
}

test {
    useJUnitPlatform()
    testLogging {
        events "passed", "skipped", "failed"
    }
}

clean {
    delete generateGrammarSource.outputDirectory
    delete generateTestGrammarSource.outputDirectory
    delete generatedSourceDir
}

compileJava.dependsOn generateGrammarSource
compileTestJava.dependsOn generateTestGrammarSource

tasks.register("benchmark", JavaExec) {
    group = "benchmark"
    dependsOn testClasses
    classpath = sourceSets.test.runtimeClasspath
    mainClass.set("at.jku.isse.ecco.adapter.rust.Benchmark")
    description = "Run the benchmark class at.jku.isse.ecco.adapter.rust.Benchmark"
    workingDir = rootProject.projectDir
}
